    name: EffectManagerPlugin
    main: com.github.n0ct.effectmanagerplugin.EffectManagerPlugin
    version: ${project.version}
    description: To put strange useless effects on players
    author: n0ct
    commands:
      em:
        description: To put strange useless effects on players.
        usage: /em list | player | effect | info | help | call
      eminfo:
        description: Retrieves informations on an existing effect.
        usage: /eminfo [<effectName>|<playerName>]
      emi:
        description: A shortcut for the eminfo command. Retrieves informations on an existing effect.
        usage: /eminfo [<effectName>|<playerName>]
      emplayer:
        description: Manages the effects associated to a player.
        usage: /emplayer add | del | clear | details | list
      emp:
        description: A shortcut for the emplayer command. Manages the effects associated to a player.
        usage: /emplayer add | del | clear | details | list
      emeffect:
        description: Manages effects definition.
        usage: /emeffect classes | help | list | details | add | del
      eme:
        description: A shortcut for the emeffect command. Manages effects definition.
        usage: /emeffect classes | help | list | details | add | del
      emcall:
        description: Call an effect directly
        usage: /emcall [<playerName> <effectName> | ( <playerName> | <effectName> )]
      emc:
        description: A shortcut for the emcall command. Call an effect directly
        usage: /emcall [<playerName> <effectName> | ( <playerName> | <effectName> )]
      emhelp:
        description: Retrieves informations about how to use that plugin.
        usage: /emhelp <command>
      emh:
        description: A shortcut for the emhelp command. Retrieves informations about how to use that plugin.
        usage: /emhelp <command>
      emlist:
        description: Retrieves a list of effect or a list of effect applied to a player
        usage: /emlist [player]
      eml:
        description: A shortcut for the emlist command. Retrieves a list of effect or a list of effect applied to a player
        usage: /emlist [player]
